"""Initial migration: Create tables for weather ETL

Revision ID: 8c25875dff53
Revises: 
Create Date: 2026-03-11 11:33:50.512815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c25875dff53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capsules',
    sa.Column('capsule_id', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('water_landings', sa.Integer(), nullable=False),
    sa.Column('land_landings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('capsule_id')
    )
    op.create_table('cores',
    sa.Column('core_id', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rtls_landings', sa.Integer(), nullable=False),
    sa.Column('asds_landings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('core_id')
    )
    op.create_table('landpads',
    sa.Column('landpad_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('locality', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('landing_attempts', sa.Integer(), nullable=False),
    sa.Column('landing_successes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('landpad_id')
    )
    op.create_table('launchpads',
    sa.Column('launchpad_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('locality', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('launch_attempts', sa.Integer(), nullable=False),
    sa.Column('launch_successes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('launchpad_id')
    )
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('registros_extraidos', sa.Integer(), nullable=False),
    sa.Column('registros_guardados', sa.Integer(), nullable=False),
    sa.Column('registros_fallidos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payloads',
    sa.Column('payload_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('mass_kg', sa.Integer(), nullable=True),
    sa.Column('orbit', sa.String(), nullable=True),
    sa.Column('customers', sa.String(), nullable=False),
    sa.Column('nationalities', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('payload_id')
    )
    op.create_table('rockets',
    sa.Column('rocket_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stages', sa.Integer(), nullable=False),
    sa.Column('boosters', sa.Integer(), nullable=False),
    sa.Column('cost_per_launch', sa.Integer(), nullable=False),
    sa.Column('success_rate_pct', sa.Integer(), nullable=False),
    sa.Column('first_flight', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('diameter_m', sa.Float(), nullable=False),
    sa.Column('mass_kg', sa.Integer(), nullable=False),
    sa.Column('engine_type', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('engine_loss_max', sa.Integer(), nullable=True),
    sa.Column('propellant_1', sa.String(), nullable=False),
    sa.Column('propellant_2', sa.String(), nullable=False),
    sa.Column('thrust_to_weight', sa.Float(), nullable=False),
    sa.Column('isp_sea_level', sa.Integer(), nullable=False),
    sa.Column('isp_vacuum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rocket_id')
    )
    op.create_table('ships',
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('home_port', sa.String(), nullable=False),
    sa.Column('mass_kg', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('launches',
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_utc', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('upcoming', sa.Boolean(), nullable=False),
    sa.Column('rocket_id', sa.String(), nullable=False),
    sa.Column('launchpad_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['launchpad_id'], ['launchpads.launchpad_id'], ),
    sa.ForeignKeyConstraint(['rocket_id'], ['rockets.rocket_id'], ),
    sa.PrimaryKeyConstraint('launch_id')
    )
    op.create_table('rocket_payload_weights',
    sa.Column('rocket_id', sa.String(), nullable=False),
    sa.Column('orbit_id', sa.String(), nullable=False),
    sa.Column('orbit_name', sa.String(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('lb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rocket_id'], ['rockets.rocket_id'], ),
    sa.PrimaryKeyConstraint('rocket_id', 'orbit_id')
    )
    op.create_table('launch_capsules',
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('capsule_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.capsule_id'], ),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.launch_id'], ),
    sa.PrimaryKeyConstraint('launch_id', 'capsule_id')
    )
    op.create_table('launch_cores',
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('core_id', sa.String(), nullable=False),
    sa.Column('landing_success', sa.Boolean(), nullable=True),
    sa.Column('landing_type', sa.String(), nullable=True),
    sa.Column('landpad_id', sa.String(), nullable=True),
    sa.Column('reused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['core_id'], ['cores.core_id'], ),
    sa.ForeignKeyConstraint(['landpad_id'], ['landpads.landpad_id'], ),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.launch_id'], ),
    sa.PrimaryKeyConstraint('launch_id', 'core_id')
    )
    op.create_table('launch_payloads',
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('payload_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.launch_id'], ),
    sa.ForeignKeyConstraint(['payload_id'], ['payloads.payload_id'], ),
    sa.PrimaryKeyConstraint('launch_id', 'payload_id')
    )
    op.create_table('launch_ships',
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.launch_id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('launch_id', 'ship_id')
    )
    op.create_table('launches_central',
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=False),
    sa.Column('rocket_name', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('payload_count', sa.Integer(), nullable=False),
    sa.Column('total_payload_mass', sa.Float(), nullable=False),
    sa.Column('core_count', sa.Integer(), nullable=False),
    sa.Column('reused_cores', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.launch_id'], ),
    sa.PrimaryKeyConstraint('launch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launches_central')
    op.drop_table('launch_ships')
    op.drop_table('launch_payloads')
    op.drop_table('launch_cores')
    op.drop_table('launch_capsules')
    op.drop_table('rocket_payload_weights')
    op.drop_table('launches')
    op.drop_table('ships')
    op.drop_table('rockets')
    op.drop_table('payloads')
    op.drop_table('metricas_etl')
    op.drop_table('launchpads')
    op.drop_table('landpads')
    op.drop_table('cores')
    op.drop_table('capsules')
    # ### end Alembic commands ###
